### ISSUE TITLE
Fails to match directories (pretty urls)

### ISSUE THREAD

**Issue by queryluke** [UNC-Libraries/ROWR#3]
If the link is to a directory (i.e., one that would have an index.html file), it should not prompt a broken link or missing file.

**Comment by cazzerson** [comment]
@queryluke Can you help me understand what is failing here? I just pushed some tests that ought to catch this and everything looks good to me.

**Comment by queryluke** [comment]
Hmm...I know this was a problem at some point. I did a rather big edit to the link_checker and may have incidentally fixed it.

Looking at the code, the only place it should matter is in the following:

[target_file_exists?](https://github.com/UNC-Libraries/ROWR/blob/master/lib/rowr/link_processor.rb#L86), uses File.exist?, but quick google search suggests that File.exist? also works with a directory path. If not, I guess it would be a simple `|| Dir.exist?`

The same goes for the [is_valid_replacement?](https://github.com/UNC-Libraries/ROWR/blob/master/lib/rowr/link_processor.rb#L95) method.

Sorry! Guess this was a non-issue.

**Comment by cazzerson** [comment]
Great--thanks for your help!
